const Data = [
    {
        id:1,
        name:'Jayson Tatum',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065648.png&h=80&w=110&scale=crop',
        height:"6'8",
        wieght:'210',
        description:'Power Forward',
    },
    {
        id:2,
        name:'Jaylen Brown',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3917376.png&h=80&w=110&scale=crop',
        height:"6'6",
        wieght:'220',
        description:'Small Forward',
    },
    {
        id:3,
        name:'Marcus Smart',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2990992.png&h=80&w=110&scale=crop',
        height:"6'3",
        wieght:'220',
        description:'Point Guard',
    },
    {
        id:4,
        name:'Al Horford',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3213.png&h=80&w=110&scale=crop',
        height:"6'9",
        wieght:'240',
        description:'Center',
    },
    {
        id:5,
        name:'Robert Williams',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066211.png&h=80&w=110&scale=crop',
        height:"6'9",
        wieght:'237',
        description:'Center',
    },
    {
        id:6,
        name:' Dennis Schroder',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032979.png&h=80&w=110&scale=crop',
        height:"6'3",
        wieght:'172',
        description:'Point Guard',
    },
    {
        id:7,
        name:'Josh Richardson',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2581190.png&h=80&w=110&scale=crop',
        height:"6'6",
        wieght:'201',
        description:'Shooting Guard',
    },
    {
        id:8,
        name:'Grant Williams',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066218.png&h=80&w=110&scale=crop',
        height:"6'6",
        wieght:'237',
        description:'Power Forward',
    },
    {
        id:9,
        name:'Aaron Nesmith',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4396909.png&h=80&w=110&scale=crop',
        height:"6'5",
        wieght:'215',
        description:'Shooting Guard',
    },
    {
        id:10,
        name:'Romeo Langford',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397008.png&h=80&w=110&scale=crop',
        height:"6'5",
        wieght:'216',
        description:'Shooting Guard',
    },
    {
        id:11,
        name:'Payton Pritchard',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066354.png&h=80&w=110&scale=crop',
        height:"6'1",
        wieght:'195',
        description:'Point Guard',
    },
    {
        id:12,
        name:'Jabari Parker',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3056600.png&h=80&w=110&scale=crop',
        height:"6'7",
        wieght:'245',
        description:'Power Forward',
    },
    {
        id:13,
        name:'Enes Freedom',
        image:'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6447.png&h=80&w=110&scale=crop',
        height:"6'10",
        wieght:'250',
        description:'Center',
    },
]
export default Data